### ISSUE TITLE
Window buttons are missing

### ISSUE THREAD

**Issue by f-l-y-b-o-y** [soreau/pixdecor#25] opened 2024-10-22 04:25 UTC
All 3 buttons went missing when I enabled the plugin. Only black boxes are drawn. When I hover mouse cursor over those boxes they change shade, and when I click they do work as intended.

Am I missing icon files? If so could you tell me where is the plugin looking for them and that's the filename scheme and type?

I really like this project and I'd love to daily drive it.

Thanks.

![241022_00-18-47](https://github.com/user-attachments/assets/6534a06a-569d-4671-aea4-6cdfdc65b5eb)

**Comment by soreau** [comment] 2024-10-22 04:31
This has already been fixed in latest pixdecor. You need at least [this commit](https://github.com/soreau/pixdecor/commit/ea7aa60fc5fd7744bae4a0f9e0d3afd9246d6eeb).

**Comment by soreau** [comment] 2024-10-22 06:26
It sounds like the problem is that you did not specify `--prefix=/usr` to meson. Without this, it installs to the default which is /usr/local. You might want to `ninja -C build uninstall` and then specify the correct prefix when reinstalling.

**Comment by f-l-y-b-o-y** [comment] 2024-10-22 06:35
You are 100% correct. Looking at it now it installed the lib file in the wrong directory. I just copied it to /usr/local/lib/wayfire and it's working now. Thanks again for your quick responses and your work. Good stuff.

![241022_02-30-16](https://github.com/user-attachments/assets/e00b0f57-45e7-4656-967c-fb922a2ed545)

**Comment by soreau** [comment] 2024-10-22 06:37
👍

**Closed by soreau** 2024-10-22 06:37 UTC
