### ISSUE TITLE
Shadow remains after window move with keys

### ISSUE THREAD

**Issue by AlexJakeGreen** [soreau/pixdecor#21] opened 2024-09-04 07:24 UTC
If a window is moved using keybindings (e.g. `Meta`+`Right`), the shadow remains on old place.

![IMG_1502](https://github.com/user-attachments/assets/9ead6dea-3921-4f94-82b3-a25de24cebcf)

**Comment by soreau** [comment] 2024-09-04 12:34
It looks like something isn't being damaged enough but this would not be the responsibility of the decoration plugin, it should be fixed in whatever plugin you have configured to use i.e. Meta+Right. By default, it would be grid plugin. However it might not happen with other decoration plugins because they do not render shadows. Are you using the shadow plugin to render shadows or pixdecor with 'rounded corners' option?

**Comment by AlexJakeGreen** [comment] 2024-09-04 12:56
I do not use shadow plugin. Here are the settings:
```
[core]
plugins = alpha autostart command expo fast-switcher grid move oswitch place resize switcher vswitch
 window-rules wm-actions scale scale-title-filter foreign-toplevel kbdd pixdecor

[pixdecor]
always_decorate = none
animate = false
bg_color = \#1C1F21FF
bg_text_color = \#B3B3B3FF
border_size = 1
csd_titlebar_height = 32
effect_color = \#E01C24FF
effect_type = none
enable_shade = true
fg_color = \#31363BFF
fg_text_color = \#FFFFFFFF
icons_path = /home/alex/.config/wayfire/icons/window-%s.png
ignore_views = none
maximized_borders = true
maximized_shadows = false
overlay_engine = rounded_corners
rounded_corner_radius = 8
shade_duration = 1000ms sigmoid
shade_modifier = <ctrl> <super> 
shade_toggle = 
shadow_color = \#00000040
shadow_radius = 0
title_font = Noto Sans, 16
title_text_align = 1
titlebar = true

[grid]
duration = 300ms circle
restore = <super> KEY_DOWN | <super> KEY_KP0
slot_b = <super> KEY_KP2
slot_bl = <super> KEY_KP1
slot_br = <super> KEY_KP3
slot_c = <super> KEY_UP | <super> KEY_KP5
slot_l = <super> KEY_LEFT | <super> KEY_KP4
slot_r = <super> KEY_RIGHT | <super> KEY_KP6
slot_t = <super> KEY_KP8
slot_tl = <super> KEY_KP7
slot_tr = <super> KEY_KP9
type = none
```

**Comment by soreau** [comment] 2024-09-04 13:04
In your config, you have `shadow_radius = 0`, which means there are no shadows. Also in your screenshot, the window appears as if maybe it was wobbling or some other transform that make the lines not parallel to the edges of the shot. I am not able to reproduce this problem, so I feel like I'm missing something.

**Comment by AlexJakeGreen** [comment] 2024-09-04 13:15
I used a phone, because an attempt to make a screenshot erases the artifact

**Comment by soreau** [comment] 2024-09-04 13:17
Actually, when I set shadow_radius to a non-zero value, I can reproduce the problem. I'll look into it.

**Comment by AlexJakeGreen** [comment] 2024-09-04 13:20
I think it was late when I tested with different shadow size, and set it to zero late night, and today just copied a part of config without recheking again. sorry. The shadow must be greater than zero. This is how I found it is shadow, not a border.

**Comment by AlexJakeGreen** [comment] 2024-09-04 13:41
Yes, the patch helps. The issue has gone with the patch applied. Thanks

**Comment by soreau** [comment] 2024-09-04 14:04
I was able to fix the problem in pixdecor, thanks for the report. This issue should close automatically when track-wlroots-0.18 is merged, so it will work without the wayfire/grid patch.

**Closed** 2024-12-18 14:14 UTC
